### ISSUE TITLE
About Golden Clues Generation

### ISSUE THREAD

**Issue by AnnaGao0827** [Yixuan423/FakeBench#3]
Hi, thank you for the excellent work! I have a few questions regarding the golden clues used as ground truth in your paper. How human experts are involved in generating these golden clues? And how are the five telltale clues of fake images selected from the 14 dimensions? Do you generate all 14 dimensions and then have human experts make the selection? Many thanks!

**Comment by Yixuanli423** [comment]
Thanks for your attention. While annotating the golden clues, we first generate as many reasonable raw annotations as possible and then recruit human experts to filter, amend, and supplement them.  NOT all the 14-dimension forgery aspects are generated since we anticipate a reasonable workload for human experts. You can adjust this process based on your application scenario and the performance of the utilized LMM expert.
